"""Observed-quote shadow execution. No retrospective daily-bar admission."""
import argparse
import copy
from datetime import datetime, time
from pathlib import Path
from decimal import Decimal
from shortterm_model import SHORT_POLICY as DEFAULT_POLICY
from alpha_portfolio import fee
from alpha_engine import immutable, render
from collect_quotes import CST
from dashboard_export import latest
from tushare_sync import read, sha
from tushare_probe import probe, selected_source, XIAODEFA_ENDPOINT


def first_session(f, dates):
    return next((d for d in dates if d >= f['eligible_from']), None)


def validate_quote(row, code, observed):
    if row.get('ts_code') != code:
        raise ValueError('报价代码缺失或不匹配')
    stamp=datetime.fromisoformat(str(row.get('trade_time','')))
    if stamp.tzinfo is None:stamp=stamp.replace(tzinfo=CST)
    stamp=stamp.astimezone(CST)
    if not time(9,30)<=observed.time()<time(9,35):
        raise ValueError('超过09:30–09:35观察窗口，不补记成交')
    if stamp.date()!=observed.date() or not time(9,30)<=stamp.time()<time(9,35):
        raise ValueError('非本交易日观察窗口的报价')
    age=(observed-stamp).total_seconds()
    if not 0<=age<=30:
        raise ValueError('报价超过30秒或时间位于未来')
    price, previous, volume=[Decimal(str(row.get(k))) for k in ('close','pre_close','vol')]
    if any(not n.is_finite() or n<=0 for n in (price,previous,volume)):
        raise ValueError('报价价格或已发生累计成交量无效')
    cap=Decimal('0.195') if code.startswith(('688','300','301')) else Decimal('0.095')
    if abs(price/previous-1)>=cap:
        raise ValueError('报价接近涨跌停，保守跳过')
    return float(price),stamp.isoformat()


def run(history, run_id):
    now=datetime.now(CST);today=now.date().isoformat()
    path, prior=latest(history,'agent')
    if not prior or not prior.get('portfolio'):raise ValueError('No initialized account')
    if (history/'opening_runs'/(run_id+'.json')).exists():raise ValueError('Run already exists')
    report=copy.deepcopy(prior);state=report['portfolio'];audit=[]
    calendar=read(history/'tushare_data/trade_cal.json')['calendars']
    dates=[]
    for exchange in ('SSE','SZSE'):
        dates.append(sorted(datetime.strptime(r['cal_date'],'%Y%m%d').date().isoformat() for r in calendar[exchange] if str(r['is_open'])=='1'))
    if dates[0]!=dates[1]:raise ValueError('Calendar disagreement')
    dates=dates[0];previous=max((d for d in dates if d<today),default=None)
    endpoint,token=selected_source()
    enabled=today in dates and time(9,30)<=now.time()<time(9,35)
    def observe(code):
        if not enabled:raise ValueError('当前不在交易日09:30–09:35观察窗口')
        if state['last_date']!=previous or state['valuation_status']!='current':raise ValueError('账户未完成上一交易日估值')
        if endpoint!=XIAODEFA_ENDPOINT or not token:raise ValueError('未配置支持实时快照的数据源')
        ts=code[2:]+'.'+code[:2].upper()
        # Refuse corporate-action days unless the same-day adjustment factor is available.
        old=read(history/'tushare_data/days'/(previous.replace('-','')+'.json'))
        old_factor=next((r['adj_factor'] for r in old['adj_factor'] if r['ts_code']==ts),None)
        factor=probe('adj_factor',{'ts_code':ts,'trade_date':today.replace('-','')},'ts_code,trade_date,adj_factor',token,endpoint)
        audit.append(factor)
        if factor['status']!='success':raise ValueError('当日复权因子尚不可核验')
        fr=[dict(zip(factor['fields'],r)) for r in factor['items']]
        if len(fr)!=1 or fr[0].get('ts_code')!=ts or fr[0].get('trade_date')!=today.replace('-','') or old_factor is None or Decimal(str(fr[0]['adj_factor']))!=Decimal(str(old_factor)):
            raise ValueError('当日除权变化或因子无法核验，暂停成交')
        quote=probe('rt_k',{'ts_code':ts},'ts_code,name,close,pre_close,vol,trade_time',token,endpoint)
        audit.append(quote)
        if quote['status']!='success' or len(quote['items'])!=1:raise ValueError('未取得单只股票有效实时快照')
        row=dict(zip(quote['fields'],quote['items'][0]));observed=datetime.now(CST)
        price,stamp=validate_quote(row,ts,observed)
        return price,{'quote_at':stamp,'observed_at':observed.isoformat(),'execution_mode':'observed-quote-v1','evidence_run':run_id,'quote_sha256':sha(quote)}
    # Exit signals must have been generated by a prior close, not today's future bar.
    for pos in list(state['positions']):
        if not pos.get('exit_signal') or pos['entry_day']>=today:continue
        if not enabled:continue
        policy=pos.get('policy',DEFAULT_POLICY)
        try:
            value,evidence=observe(pos['symbol'])
            price=round(value*(1-policy['slippage']),2);gross=round(price*pos['shares'],2);cost=fee(gross,'sell');pnl=round(gross-cost-pos['cost'],2)
            state['cash']=round(state['cash']+gross-cost,2)
            state['trades'].append({'id':pos['id']+'-exit','prediction_id':pos['id'],'symbol':pos['symbol'],'side':'sell','date':today,'price':price,'shares':pos['shares'],'fee':cost,'pnl':pnl,'return_pct':round(pnl/pos['cost']*100,4),'reason':pos['exit_signal'],**evidence})
            state['positions'].remove(pos)
        except (ValueError,OSError,KeyError,ArithmeticError) as exc:
            audit.append({'symbol':pos['symbol'],'side':'sell','status':'deferred','reason':str(exc)[:200]})
    for f in sorted(report['forecasts'],key=lambda f:(f['created_at'],f['id'])):
        if not f['paper_eligible'] or f['id'] in state['attempted']:continue
        due=first_session(f,dates)
        if due is None or due>today or (due==today and now.time()<time(9,30)):continue
        reason=None;evidence={};policy=f.get('policy',DEFAULT_POLICY)
        try:
            if due!=today or not enabled:raise ValueError('错过首个允许交易日的观察窗口，不回填日线成交')
            if f.get('execution_mode')!='observed-quote-v1':raise ValueError('旧日线撮合计划不迁移为新执行方式，等待新版本计划')
            created=datetime.fromisoformat(f['created_at']).astimezone(CST)
            if created.date()>now.date() or (created.date()==now.date() and created.time()>=time(9,20)):raise ValueError('计划未在09:20之前冻结')
            if f['as_of']!=previous:raise ValueError('计划依据不是上一交易日，不执行过期计划')
            if state['paused'] or len(state['positions'])>=policy['max_positions']:raise ValueError('风险暂停或持仓已满')
            if any(p['symbol']==f['symbol'] for p in state['positions']):raise ValueError('已经持有该股票')
            value,evidence=observe(f['symbol'])
            if not policy['entry_gap_min']<=value/f['reference_price']-1<=policy['entry_gap_max']:raise ValueError('观察时报价偏离参考价超过3%')
            price=round(value*(1+policy['slippage']),2)
            budget=min(state['equity']*policy['max_weight'],state['equity']*policy['risk_per_trade']/policy['stop_pct'],state['cash']-10)
            shares=max(0,int(budget/price/100)*100)
            if shares<=0 or (f['symbol'].startswith('sh688') and shares<200):raise ValueError('资金不足最低模拟申报数量')
            cost=fee(round(price*shares,2),'buy');total=round(price*shares+cost,2)
            if total>state['cash']:raise ValueError('现金不足以支付数量与费用')
            state['cash']=round(state['cash']-total,2)
            state['positions'].append({'id':f['id'],'symbol':f['symbol'],'name':f['name'],'shares':shares,'entry_day':today,'entry_price':price,'cost':total,'exit_signal':None,'mark':value,'value':round(value*shares,2),'policy':policy})
            state['trades'].append({'id':f['id']+'-entry','prediction_id':f['id'],'symbol':f['symbol'],'side':'buy','date':today,'price':price,'shares':shares,'fee':cost,'reason':'观察窗口有效报价满足冻结计划',**evidence})
        except (ValueError,OSError,KeyError,ArithmeticError) as exc:reason=str(exc)[:200]
        state['attempted'].append(f['id'])
        if reason:state['trades'].append({'id':f['id']+'-skip','prediction_id':f['id'],'symbol':f['symbol'],'side':'skipped','date':today,'reason':reason,**evidence})
    report.update(id=run_id,generated_at=datetime.now(CST).isoformat())
    report['issues']=['开盘观察执行记录；当日净值仍需收盘估值。未用当天完整日线决定成交。']+[r['reason'] for r in audit if r.get('status')=='deferred']
    if any(t.get('evidence_run')==run_id for t in state['trades']):
        state['equity']=round(state['cash']+sum(p['value'] for p in state['positions']),2)
        state['nav']=round(state['equity']/DEFAULT_POLICY['capital'],6)
        state['valuation_status']='intraday'
    immutable(history/'opening_runs'/(run_id+'.json'),{'generated_at':report['generated_at'],'window_enabled':enabled,'audit':audit})
    dest=history/'agent'/(run_id+'.json');immutable(dest,report);dest.with_suffix('.md').write_text(render(report))
    print('Observed execution archived; window enabled:',enabled)


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--history',type=Path,required=True);p.add_argument('--run-id',required=True)
    a=p.parse_args();run(a.history,a.run_id)
